### ISSUE TITLE
Allow adjustment of OS-specific defaults

### ISSUE THREAD

**Issue by njm506** [yo61/puppet-logrotate#9]
(Originally opened against the parent repository, but would be a useful improvement here) -

logrotate::defaults defines the logrotate::rule for things like wtmp and btmp.  As the parameters aren't exposed, I can't change the rotation settings for these.

Would it be possible to add options to the logrotate class (in init.pp) to bypass defining these resources, so I can define them elsewhere with the settings I need, while still setting up logrotate.conf appropriately?

**Comment by robinbowes** [comment]
A simple way to do this would be to add an "include_os_defaults" parameter, which is "true" by default. If set to false, the defaults class is not included. How does that sound?

**Comment by njm506** [comment]
That would certainly do the job nicely!

**Comment by amiryal** [comment]
See also [this commit](https://github.com/seekingalpha/puppet-logrotate/commit/5b4e9089f802dfecca51cc2ef48851600c9c148d), which will let you leave the ***real*** OS defaults alone.  Anyone is welcome to improve on that patch, update the test suite and submit a PR.

IMO, leaving the OS defaults alone should have been the default behaviour,  since OS detection code is fragile – a common problem with Puppet modules – which is better just being avoided.

**Comment by robinbowes** [comment]
@amiryal PRs with tests always gratefully received. :)
